### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by tombruh** [natsuminoneko/wg#1]
Ran maplelegends, then ran this as admin.
Window opened but checkbox doesn't do anything. It seems it found maplelegends because if maplelegends isn't open it fails with a message about not finding it. No indication of where the problem is. Let me know if there are steps I'm missing or something.

**Comment by natsuminoneko** [comment]
A new realese version has been pushed. I am terribly sorry for this bug.

**Comment by tombruh** [comment]
> A new realese version has been pushed. I am terribly sorry for this bug.

Thanks, just tried it out and it's working.
